security:
  user:
    name: buzz
    password: infinity

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

#logging:
#  level:
#    org.springframework.data.rest: debug

spring:
  data:
    rest:
      base-path: /data-api
  datasource:
    url: jdbc:h2:mem:tacocloud

---
spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
  config:
    activate:
      on-profile: prod

logging:
  level:
    tacos: WARN
